### ISSUE TITLE
Wann kommt Release 1.0?

### ISSUE THREAD

**Issue by LMStudent** [LernMoment/einstieg-csharp-taschenrechner#1]
Hallo @suchja, kannst du mir sagen, wann das offizielle Release 1.0 erscheint?

**Comment by suchja** [comment]
Das wird spätestens morgen erscheinen. Ich habe es bereits fertig, aber muss es noch auf GitHub veröffentlichen. Ich lasse dieses Issue offen, bis das Release da ist.

**Comment by suchja** [comment]
Endlich ist Release 1.0 verfügbar. Sämtliche Änderungen sind über die Historie verfügbar.
