### ISSUE TITLE
Test Issue (Udemy Kurs Teilnehmer)

### ISSUE THREAD

**Issue by bungyschaf** [LernMoment/einstieg-csharp-taschenrechner#107]
Übung 1 - ein Issue erstellen.... 

#102  mir geht's auch so ...

hoffentlich kann ich dieses issue dann wieder löschen - wenn nicht bitte ignorieren...!

**Comment by suchja** [comment]
@bungyschaf Sehr gut! Leider braucht mein "Bot" noch ein wenig mehr Wissen. Daher musst du nun persönlich mit mir vorlieb nehmen 😉.
Natürlich brauchst du das Issue nicht löschen. Wo es nun geschlossen ist, wird es sowieso nur noch selten angezeigt. 
Super, dass du auch gleich ausprobiert hast wie das mit dem verlinken geht. Hast du mal in #102 geschaut und gesehen, dass dort automatisch ein Link auf dein Issue hier eingefügt wurde?
Wie du nun siehst kann man auch an bereits geschlossenen Issues Kommentare verfassen. Du als Autor und ich als Projektinhaber können sogar das Issue wieder öffnen. Wenn du magst, kannst du es ausprobieren.

Ich hoffe, dass ich dann auch bald einen PullRequest von dir sehe. 

Weiterhin viel Spaß hier auf GitHub und bis zum PullRequest!

Jan von LernMoment.de

**Comment by bungyschaf** [comment]
oh wow!!! der kursleiter schreibt mir persönlich - fühle mich geehrt, danke :-)
 

 

habe deinen kurs schon vor längerem gekauft und jetzt in den ferien (bin lehrer) endlich(!!!)

mal zeit diesen durchzuackern :-)  bin auch schon fast durch damit, werde ihn heute noch abschließen.

 

meine schüler (aus der computer/programmier ag) kennen alle schon längst git und ziehn mich

fast schon damit auf, wann ich denn endlich meine prg. und aufgaben für sie nicht mehr per mail/stick

verteile sondern per git... wird dann jetzt hoffentlich soweit sein. ich hab mir heute für 4 € die git pro

version geleistet, da ich nicht will, dass an meinen projekten für die schüler alle welt zugucken kann...

 

kurzes feedback zu deinem kurs noch:

 

war sehr gut angelegtes geld für diesen kurs, war nur am anfang etwas enttäuscht, dass ich

nicht alle buttons und anklick-möglichkeiten auf der git seite gefunden habe, wie sie in den kursvideos

von dir gezeigt werden - aber da hat sich halt github weiterentwickelt und man /ich komm dann schon

zurecht damit, dass es nicht mehr 1:1 so aussieht wie in deinem kurs.

 

werde also am ende natürlich die 5 sterne vergeben :-)

 

übrigens ein letztes noch: mein guter vorsatz für 2021 ist auch mal selber einen udemy kurs zu erstellen,

thema: quanten computing, wahrscheinlich eher ein nischenthema - von der teilnehmerzahl die du mit

diesem kurs erreicht hast, kann ich nur träumen, gratuliere :-)

 

 

viele grüße, muss jetzt noch den kurs fertigkriegen.

 

rené

 

 

 

 

 

 

 


----------------------------------------------------------------------------------------------------------------------

 
 

Gesendet: Dienstag, 29. Dezember 2020 um 00:12 Uhr
Von: "Jan Suchotzki" <notifications@github.com>
An: "LernMoment/einstieg-csharp-taschenrechner" <einstieg-csharp-taschenrechner@noreply.github.com>
Cc: "bungyschaf" <rene.gruenbauer@web.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [LernMoment/einstieg-csharp-taschenrechner] Test Issue (Udemy Kurs Teilnehmer) (#107)


 

@bungyschaf Sehr gut! Leider braucht mein "Bot" noch ein wenig mehr Wissen. Daher musst du nun persönlich mit mir vorlieb nehmen 😉.
Natürlich brauchst du das Issue nicht löschen. Wo es nun geschlossen ist, wird es sowieso nur noch selten angezeigt.
Super, dass du auch gleich ausprobiert hast wie das mit dem verlinken geht. Hast du mal in #102 geschaut und gesehen, dass dort automatisch ein Link auf dein Issue hier eingefügt wurde?
Wie du nun siehst kann man auch an bereits geschlossenen Issues Kommentare verfassen. Du als Autor und ich als Projektinhaber können sogar das Issue wieder öffnen. Wenn du magst, kannst du es ausprobieren.

Ich hoffe, dass ich dann auch bald einen PullRequest von dir sehe.

Weiterhin viel Spaß hier auf GitHub und bis zum PullRequest!

Jan von LernMoment.de
