### ISSUE TITLE
Test Udemy -FAbio

### ISSUE THREAD

**Issue by LoginFabio** [LernMoment/einstieg-csharp-taschenrechner#12]
Abschnitt Lektion2 Test bei Udemy

**Comment by suchja** [comment]
@LoginFabio 

Hallo Fabio!

Herzlichen Glückwunsch zu deinem (ersten?) Issue! In #DailyGitHub (einer Videoserie die ich momentan nicht fortsetze) habe ich einiges zur Markdown Syntax erklärt. Damit kannst du schnell formatierten Text schreiben. Weiteres dazu findest du [hier](https://github.com/LernMoment/DailyGitHub/blob/master/ShowNotes.md#wichtige-markdown-elemente-für-issues--pull-requests--episode-6).

Probier doch gleich mal wie es ist ein Issue zu schließen. Das kannst du als Autor des Issues machen oder auch ich als Projektinhaber.

**Comment by suchja** [comment]
@LoginFabio Hallo Fabio, wahrscheinlich hat sich dieses Thema für dich erledigt, oder? Wenn du magst, dann schließe dieses Issue doch bei Gelegenheit.  😄 

Wenn ich nichts weiter höre, dann mache ich das die Tage. Vielen Dank für die Teilnahme an einem LernMoment-Kurs/Tutorial!

Viele Grüße
Jan von LernMoment.de

------------------------
🚀 NEU von LernMoment: Übe mit mir professionelle Softwareentwicklung in C# - [Starte jetzt zum Einführungspreis](https://www.udemy.com/csharp-uebungskurs-einfach-verschluesselt/?couponCode=GH-FOOTER-UROT-10)
