### ISSUE TITLE
Migration .net6.0

### ISSUE THREAD

**Issue by MK-NEUKO** [LernMoment/einstieg-csharp-taschenrechner#128]
@suchja ich hebe keine Berechtigung einen neuen Branch zu erstellen.
Ich würde gerne die Migration zu .net 6.0 machen. Ich mache erstmal einen Fork und schicke dir dann einen Pull Request.

**Comment by suchja** [comment]
#129 akzeptiert. Wenn es diesbezüglich noch weiteren Diskussionsbedarf gibt, bitte neues Issue öffnen, oder falls sinnvoll in #129 kommentieren.
