### ISSUE TITLE
Ein Test Issue :)

### ISSUE THREAD

**Issue by AzaliaBerlin** [LernMoment/einstieg-csharp-taschenrechner#13]
@suchja 
Ist einfach zum testen.

**Comment by suchja** [comment]
@AzaliaBerlin läuft ;-)!

Du als Autor dieses Issues kannst es auch selber wieder schließen, wenn du möchtest.

**Comment by suchja** [comment]
PERFEKT!!!

Wie du siehst kann ein Issue auch noch kommentiert werden, wenn es schon geschlossen ist.
