### ISSUE TITLE
Ist der TR auch ohne Form nutzbar?

### ISSUE THREAD

**Issue by morfeus3009** [LernMoment/einstieg-csharp-taschenrechner#137]
Hallo,

ich wollte gerne wissen, ob denn der TR hier auch für Einsteiger ist, die bisher noch keine Forms hatten?
Also nur Console und Schleifen etc.
Danke für die RM.

Gruß, Jochen

**Comment by suchja** [comment]
@morfeus3009 Hallo Jochen,
Tatsächlich ist der TR ein Konsolenprojekt ganz ohne Forms. Keine Ahnung ob du gerne Forms lernen möchtest oder nicht. 

Liebe Grüße 
Jan
