### ISSUE TITLE
Übung Test Issue  

### ISSUE THREAD

**Issue by JamieBe** [LernMoment/einstieg-csharp-taschenrechner#14]
@suchja Erster Issue Github Tutorial.

**Comment by suchja** [comment]
@Jamiebe Vielen Dank, dass du am Tutorial teilgenommen hast! Das mit dem Issue läuft auch super. 
Wenn du magst, kannst du es auch selber schließen. Der Autor eines Issues ist dazu nämlich berechtigt.

**Comment by JamieBe** [comment]
@suchja Danke für deine schnelle Antwort

**Comment by suchja** [comment]
@JamieBe sehr gerne! Wie sieht es aus mit einem PullRequest?
