### ISSUE TITLE
Wie lange dauert es, bis ein Udemy-Test-Issue beantwortet wird?

### ISSUE THREAD

**Issue by aDabbelju** [LernMoment/einstieg-csharp-taschenrechner#146]
In dem Udemy-Kurs "Tutorial: Grundlagen von GitHub - Fork, Pull Request und Co." wurde aufgerufen ein Issue zu erstellen. Nun stelle ich mir die Frage, wie lange es wohl dauern wird, bis eine Antwort auf meine Frage hier erscheint. :-)

**Comment by suchja** [comment]
@aDabbelju Eine Antwort (wenn auch automatisiert) hast du ja direkt erhalten ;-).

Eine persönliche kommt nach 2 Tagen. Für einen kostenlosen Kurs nicht schlecht, oder ;-). 

Nachdem du nun weißt wie du ein Issue schließt, verrate ich dir auch wie du es wieder öffnest. Du als Autor des Issues wie auch ich als Projektinhaber hast das Recht ein Issue wieder zu öffnen. Wenn du magst, kannst du es gleich mal ausprobieren.

**Comment by aDabbelju** [comment]
@suchja Da das erneute öffnen geklappt hat, schließe ich diesen Issue mal wieder :-)

**Comment by suchja** [comment]
Wie du siehst, kannst du auch kommentieren, wenn ein Issue geschlossen ist.

Außerdem gibt es eine Fülle von Emojis die du direkt in Markdown verwenden kannst. Markdown ist die Beschreibungssprache die du verwendest für die Issues. 

[Hier](https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md) eine Übersicht der Emojis (sofern du sie nicht anderweitig auf deinem System direkt einsetzen kannst).
