### ISSUE TITLE
Udemy TestIssue

### ISSUE THREAD

**Issue by beinando** [LernMoment/einstieg-csharp-taschenrechner#15]
@suchja  Test Issue123

**Comment by suchja** [comment]
@Matzk hat geklappt! Vielen Dank, dass du am Tutorial teilgenommen hast!
Als Autor eines Issues kannst du es auch selber schließen. Probier es doch gleich mal aus.

**Comment by suchja** [comment]
@beinando Scheinbar habe ich den falschen Benutzernamen verwendet und so wurdest du nicht weiter informiert. Wenn du magst, kannst du dieses Issue selber schließen. Wenn nicht, dann mache ich das die Tage.

Vielen Dank für die Teilnahme an einem LernMoment-Kurs/Tutorial!

Viele Grüße
Jan von LernMoment.de

------------------------
🚀 NEU von LernMoment: Übe mit mir professionelle Softwareentwicklung in C# - [Starte jetzt zum Einführungspreis](https://www.udemy.com/csharp-uebungskurs-einfach-verschluesselt/?couponCode=GH-FOOTER-UROT-10)

**Comment by suchja** [comment]
@beinando Sehr cool! Hast du noch Lust auch einen PullRequest zu machen? Kannst du entweder hier machen oder bei lmstudent/hallo-github
