### ISSUE TITLE
Übung Udemy

### ISSUE THREAD

**Issue by RaySound** [LernMoment/einstieg-csharp-taschenrechner#155]
#100 mein Test Issues

**Comment by suchja** [comment]
@RaySound Perfekt!

Nachdem du nun weißt wie du ein Issue schließt, verrate ich dir auch wie du es wieder öffnest. Du als Autor des Issues (wie auch ich als Projektinhaber) hast das Recht ein Issue wieder zu öffnen. Wenn du magst, kannst du es gleich mal ausprobieren.

Achte bitte auch auf den kleinen Pfeil neben dem reopen/close Button. Damit kannst du insbesondere, wenn das Issue geöffnet ist, auswählen, ob die es als completed schließen willst, oder als nicht geplant. Damit kannst das Projektinhaber oder das Team des Projektes anzeigen ob das Thema wirklich erledigt wurde, oder ob es als "irrelevant" geschlossen wurde.
