### ISSUE TITLE
Danke!

### ISSUE THREAD

**Issue by SchweizerSchoggi** [LernMoment/einstieg-csharp-taschenrechner#16]
Hallo Jan, vielen Dank für den prima Kurs!!

**Comment by suchja** [comment]
@SchweizerSchoggi Sehr gerne! Freut mich, wenn es dir geholfen hat. Gerne bin ich dir weiterhin bei Themen rund um die Softwareentwicklung behilflich. Melde dich einfach 😉 

**Übrigens:** Du kannst dieses Issue selber wieder schließen, weil du der Autor bist. Sowohl Autor wie auch Projektinhaber haben zum Schließen die Berechtigung.

Viele Grüße
Jan von LernMoment.de

------------------------
🚀 NEU von LernMoment: Übe mit mir professionelle Softwareentwicklung in C# - [Starte jetzt zum Einführungspreis](https://www.udemy.com/csharp-uebungskurs-einfach-verschluesselt/?couponCode=GH-FOOTER-UROT-10)
