### ISSUE TITLE
ÜBUNG: Erstelle ein Issue Abschnitt 2, Lektion 6

### ISSUE THREAD

**Issue by sap4all-live** [LernMoment/einstieg-csharp-taschenrechner#19]
Wass soll ich Posten?

Eventuell dass hier ...

Nur ein kleiner Tippfehler auf deiner Webseite http://www.lernmoment.de/

Wenn du anfängst Programmieren zu lernen, dann fragst du dich bestimmt wo du anfangen sollst? Was sind die ersten Schritten?

Ok, Übung erledigt :-)

**Comment by suchja** [comment]
@sap4all-live Hallo Dirk, das ist doch schon mal super! Es geht ja einfach nur darum, dass du überhaupt was praktisch umsetzt.

Ein kleiner Tipp noch zur Markdown-Syntax (darin werden Issues, README usw. geschrieben): Wenn du Links in deinen Text einfügen willst, dann kannst du einfach die URL schreiben (wie du es bei http://www.lernmoment.de bereits gemacht hast). GitHub setzt es dann automatisch auf einen Link um.
Du kannst aber auch einen anderen Text als Link markieren (z.B. weitere Details findest du [hier](http://www.lernmoment.de)). Dazu setzt du den gewünschten Text einfach in eckige Klammern und **direkt** danach (also ohne Leerzeichen) die URL in runde Klammern.

Weiterhin viel Spaß auf GitHub und mit dem Kurs.
