### ISSUE TITLE
ÜBUNG: Erstelle ein Issue Abschnitt 2, Lektion 6

### ISSUE THREAD

**Issue by stepweII** [LernMoment/einstieg-csharp-taschenrechner#20]
Die Übung führt leider zu Duplikaten...

**Comment by suchja** [comment]
@stepweII Herzlich Willkommen auf GitHub und super, dass du auch die Übungen aus meinem Kurs umsetzt!!!

Um nicht viele dieser Duplikate zu haben, könntest du ausprobieren das Issue gleich wieder zu schließen. Du also Autor des Issues so wie ich als Projektinhaber können ein Issue schließen.

Ich wünsche dir weiterhin viel Spaß im Kurs und hoffe dich auch in einem meiner anderen Kurs begrüßen zu dürfen.

Viele Grüße
Jan von LernMoment.de

**Comment by stepweII** [comment]
duplicate issue
