### ISSUE TITLE
Test Issue fuer den kostenfreien GitHub Kurs 

### ISSUE THREAD

**Issue by marcclange** [LernMoment/einstieg-csharp-taschenrechner#21]
Das ist nur eine Uebung fuer den sehr hilfreichen GitHub Kurs. Vielen Dank fuer diesen Kurs!

**Comment by suchja** [comment]
@marcclange Herzlich willkommen! Freut mich das der Kurs dir helfen konnte!

Wenn du magst kannst du gleich ausprobieren dieses Issue wieder zu schließen. Sowohl du als Autor als auch ich als Projektinhaber können das Issues schließen. Andere Personen können das nicht. Es kann jedoch jeder angemeldete Benutzer einen Kommentar am Issue hinterlassen.

**Comment by marcclange** [comment]
@suchja vielen Dank fuer diese schnelle Antwort! :) Ich hoffe Sie haben einen schoenen Abend!
