### ISSUE TITLE
Testissue und allgemeine Frage

### ISSUE THREAD

**Issue by dannypilz** [LernMoment/einstieg-csharp-taschenrechner#23]
kann man Programme aus .NET auch nachträglich in github hochstellen und wenn ja, wie schafft man es die Ordnungsstruktur beizubehalten, wie du es hier getan hast?

Viele Grüße
Danny 

P.S. Ich finde deinen Kurs bis jetzt sehr gut! :)

**Comment by suchja** [comment]
@dannypilz 
ist schon eine Weile her, dass du dieses Frage gestellt hast (ENTSCHULDIGUNG).

Ich hoffe du hast bereits eine Antwort gefunden. Wenn nicht einfach nochmal melden!!!
