### ISSUE TITLE
noch ein Testissue

### ISSUE THREAD

**Issue by wjsteiner** [LernMoment/einstieg-csharp-taschenrechner#24]
@suchja  

Q1: Wozu sollte ich Markdown verwenden? Dazu gibt's doch im 21. Jahrhundert die Funktionsbuttons oben. _test italics_ funktioniert tadellos
Q2: Ist es möglich, in der Git und GitHub Welt zu überleben, ohne command prompts und kryptische Unix-style commandos mit zig options zu kennen?

#20 hiermit erledigt.

Gruß,
wjsteiner

**Comment by suchja** [comment]
@wjsteiner Vielen Dank für deine Fragen!

A zu Q1: Das ist natürlich eine Frage der persönlichen Präferenz. Ich arbeite sehr viel mit Issues auf GitHub und schreibe auch meinen Blog [LernMoment.de](www.lernmoment.de) mit Markdown. Ich bin schneller, wenn ich gerade die entsprechende Markdown Syntax schreibe, als wenn ich für jede Formatierung erst die Tastatur verlasse und mit der Maus den passenden Funktionsbutton betätige.
A zu Q2: Das ist definitiv möglich. Die meisten Entwicklungsumgebungen (wie zum Beispiel Visual Studio) bringen bereits eine Oberfläche für Git mit. Zusätzlich bietet GitHub selber eine entsprechende Oberfläche an: [GitHub Desktop](https://desktop.github.com).
Mit den Oberflächen kannst bereits viele der Aufgaben erledigen, die du auch über die Kommandozeile umsetzen kannst. Allerdings musst du auch bei der Oberfläche wissen was es genau bedeutet und welche Funktion du wann anwenden musst. Git kommt halt aus der Linux-Ecke und somit findest du die meiste Dokumentation für die Kommandozeile.

Konnte ich damit deine Fragen beantworten?

Viele Grüße
Jan von [LernMoment](www.lernmoment.de)

--------------------------------------------
Mehr zum Thema GitHub von LernMoment im Online-Kurs ["Einstieg in GitHub - Entwickle Software wie die Profis"](http://www.lernmoment.de/einstieg-github/)

**Comment by wjsteiner** [comment]
Jan,

vielen Dank für die prompte Reaktion.

Meine Erfahrung ist dass man es mit ziemlich vielen Nerds zu tun hat die nur in Kommandozeilen-Syntax denken.
Das habe ich mir nach DOS eigentlich abgewöhnt und versuche es zu vermeiden.
Aber gerade bei Installationen irgendwelcher Pakete im Open-Source Umfeld kommt man meist nicht daran vorbei.
Wobei die Syntax dann noch von Unix-Systemen kopiert wird und gelegentlich im DOS Prompt so nicht läuft.

Danke für die Git Schulung, war hilfreich.

Gruß,
Wolfgang


Von: Jan Suchotzki [mailto:notifications@github.com]
Gesendet: Donnerstag, 5. April 2018 17:27
An: LernMoment/einstieg-csharp-taschenrechner <einstieg-csharp-taschenrechner@noreply.github.com>
Cc: wjsteiner <wjsteiner@hotmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [LernMoment/einstieg-csharp-taschenrechner] noch ein Testissue (#24)


@wjsteiner<https://github.com/wjsteiner> Vielen Dank für deine Fragen!

A zu Q1: Das ist natürlich eine Frage der persönlichen Präferenz. Ich arbeite sehr viel mit Issues auf GitHub und schreibe auch meinen Blog LernMoment.de<www.lernmoment.de> mit Markdown. Ich bin schneller, wenn ich gerade die entsprechende Markdown Syntax schreibe, als wenn ich für jede Formatierung erst die Tastatur verlasse und mit der Maus den passenden Funktionsbutton betätige.
A zu Q2: Das ist definitiv möglich. Die meisten Entwicklungsumgebungen (wie zum Beispiel Visual Studio) bringen bereits eine Oberfläche für Git mit. Zusätzlich bietet GitHub selber eine entsprechende Oberfläche an: GitHub Desktop<https://desktop.github.com>.
Mit den Oberflächen kannst bereits viele der Aufgaben erledigen, die du auch über die Kommandozeile umsetzen kannst. Allerdings musst du auch bei der Oberfläche wissen was es genau bedeutet und welche Funktion du wann anwenden musst. Git kommt halt aus der Linux-Ecke und somit findest du die meiste Dokumentation für die Kommandozeile.

Konnte ich damit deine Fragen beantworten?

Viele Grüße
Jan von LernMoment<www.lernmoment.de>

________________________________

Mehr zum Thema GitHub von LernMoment im Online-Kurs "Einstieg in GitHub - Entwickle Software wie die Profis"<http://www.lernmoment.de/einstieg-github/>

**Comment by suchja** [comment]
Hallo Wolfgang,

ich verstehe was du meinst und habe auch lange versucht mich gegen die Kommandozeile zu wehren. Letztlich habe ich für mich festgestellt, dass auch das nur Gewohnheit ist. Mich hat überzeugt, dass ich häufig die Dinge besser verstehe, wenn ich die Kommandozeile verwende, weil ich mich tiefer mit der Materie beschäftige. Das ist jedoch sicherlich sehr subjektiv.

Freut mich, dass dir mein Tutorial gefallen hat. Wäre super, wenn du es bewerten und weiterempfehlen könntest.

Vielen Dank und viel Spaß mit GitHub
Jan von [LernMoment](www.lernmoment.de)
