### ISSUE TITLE
weiterer Testissue 

### ISSUE THREAD

**Issue by RikoNev** [LernMoment/einstieg-csharp-taschenrechner#25]
Danke!

**Comment by suchja** [comment]
@RikoNev 😃 WILLKOMMEN auf GitHub 🚀

Freut mich das du dich hier mit meinem Kurs einarbeitest. Wenn du magst kannst du gleich mal eine weitere Aktion machen:

Schließe dieses Issue wieder. Sowohl der Autor (also du) wie auch der Projektinhaber können das machen. Aber ich überlasse natürlich dir die Ehre ;-)!

Weiterhin viel Spaß
Jan von [LernMoment.de](http://www.lernmoment.de/einstieg-github/)

**Comment by RikoNev** [comment]
Alles klar! Danke für deine schnelle Rückmeldung :)
