### ISSUE TITLE
ÜBUNG: Erstelle ein Issue

### ISSUE THREAD

**Issue by MartinDennis** [LernMoment/einstieg-csharp-taschenrechner#26]
Abschnitt 2, Lektion 6
Hiermit umgesetzt. 

Grüße, Martin

**Comment by suchja** [comment]
@MartinDennis Willkommen bei LernMoment und auf GitHub! Freut mich sehr, dass du einen meiner Kurse belegst!

Damit du mit dieser kleinen Übung noch gleich ein wenig mehr lernst hier noch ein Hinweise:

Du also Autor kannst ein Issue auch wieder schließen. Neben dem Autor kann ein Issue nur durch den Projektinhaber geschlossen werden. Probier es doch einfach mal aus.

Dir weiterhin viel Spaß und Erfolg mit meinen Kursen und natürlich hier auf GitHub
Jan von [LernMoment](www.lernmoment.de)

**Comment by MartinDennis** [comment]
Danke werde ich haben.

Jetzt geht es weiter mit
"Einstieg in C# - Software programmieren wie ein Profi"
auf dass, das Projekt für die Uni ein Erfolg wird.

Grüße, Martin

**Comment by suchja** [comment]
@MartinDennis Übrigens: Du kannst ein Issue auch kommentieren, wenn es schon geschlossen wurde. Als Projektinhaber und Autor kannst du es sogar wieder öffnen.

Viel Erfolg bei deinem Uni-Projekt und sag Bescheid, wenn ich irgendwie helfen kann.
