### ISSUE TITLE
Ein Test-Issue

### ISSUE THREAD

**Issue by StefanRieger** [LernMoment/einstieg-csharp-taschenrechner#28]
Arbeite gerade am Kurs: "Grundlagen von GitHub" und kann den Kurs nur jedem empfehlen, die den Einstieg suchen.

**Comment by suchja** [comment]
@StefanRieger Super! Herzlich willkommen bei GitHub und LernMoment! Außerdem natürlich herzlichen Glückwunsch zu deinem ersten Issue!

Als Autor kannst du dieses Issue auch wieder schließen. Magst du es ausprobieren?

**Comment by StefanRieger** [comment]
- Closed -

**Comment by suchja** [comment]
@StefanRieger Perfekt! Wie du siehst kann man sogar auch bereits geschlossene Issues noch kommentieren. Der Projektinhaber hat jedoch die Möglichkeit für ein Issue die Kommentare zu schließen.
Der Projektinhaber kann auch ein Issue zu einer späteren Zeit wieder öffnen.
