### ISSUE TITLE
Ein Issue-Test - relativ sinnfrei

### ISSUE THREAD

**Issue by API17** [LernMoment/einstieg-csharp-taschenrechner#29]
Es ist eine gelungene Idee, dass es möglich ist, an einem Beispiel-Projekt beliebig ohne Stress üben zu können.

> Dieses ist also ein Quote...

`Code gibt es auch`

### So sieht ein Header aus?

- Test 1

1. Komisch mit der Liste
2. Warum zählt der nicht weiter?
3. Ach so geht das...

@gustda Wer ist du denn?

 #
[Hello World - PDF.pdf](https://github.com/LernMoment/einstieg-csharp-taschenrechner/files/2271894/Hello.World.-.PDF.pdf)

**Comment by suchja** [comment]
@API17 Herzlich willkommen und super, dass du von den Übungen so ausführlich gebrauch machst. Das wird dir langfristig richtig weiter helfen.

Du kannst auch gleich mal probieren das Issue zu schließen! Das kannst du als Autor und ich als Projektinhaber. Der @gustda kann das auch, weil es ein Mitarbeiter in meinem Team ist. D.h. GitHub hat auch ein Rechtemanagement mit dem man weiteren Personen gewisse Rechte einräumen kann.
