### ISSUE TITLE
Ich bin auch ein Test-Issues 

### ISSUE THREAD

**Issue by Alpackisback** [LernMoment/einstieg-csharp-taschenrechner#31]
Hallo @suchja vielen Lieben Dank für Ihren kostenlosen Kurs bei Udemy...

**Comment by suchja** [comment]
Sehr gerne. Schön, dass sie auch die Übungen machen.

**Comment by suchja** [comment]
Übrigens, als Autor können Sie das Issue auch gleich wieder schließen.
