### ISSUE TITLE
Auch ich bin ein Test Issue

### ISSUE THREAD

**Issue by SteveAusBerlin** [LernMoment/einstieg-csharp-taschenrechner#32]
Ich teste mal die verschiedenen Optionen. #28 
@suchja ich danke dir für diesen Kurs, er hilft mir wirklich weiter. 

Gruß Steve

**Comment by suchja** [comment]
@SteveAusBerlin Glückwunsch zu deinem ersten Issue und herzlich willkommen auf GitHub und LernMoment.de ! Freut mich sehr, dass du mit meinem Kurs etwas lernen konntest.

Hoffe du bleibst dran! Wenn ich mir deine Geschichte so anschaue, dann habe ich da aber keine Bedenken 😉.

Übrigens kannst du als Autor dieses Issue auch wieder schließen. Natürlich könnte ich als Projektinhaber das auch machen, aber du willst ja was lernen ;-).

Viele Grüße aus Bielefeld
Jan
