### ISSUE TITLE
Testissue

### ISSUE THREAD

**Issue by BaSTeD** [LernMoment/einstieg-csharp-taschenrechner#34]
Ein Testissue wie #32

@suchja toller Kurs

**Comment by suchja** [comment]
@BaSTeD Vielen Dank! Freut mich, dass du dabei bist. 

Als Autor des Issue kannst du es selber wieder schließen, aber das hast du bestimmt schon gelesen, oder 😉? Vielleicht magst du es einfach mal ausprobieren?

Viele Grüße und einen schönen Samstag noch
Jan von LernMoment.de

**Comment by BaSTeD** [comment]
Ok, issue closed :)
