### ISSUE TITLE
Und noch ein Testissue

### ISSUE THREAD

**Issue by sboutizla** [LernMoment/einstieg-csharp-taschenrechner#35]
@suchja hallo Jan, vielen Dank für diesen interessanten Kurs, der auch noch kostenlos ist 👍

**Comment by suchja** [comment]
@sboutizla Hallo Said, sehr gerne! Freut mich, dass er dir geholfen hat!!!

Du als Autor kannst dieses Issue auch wieder schließen. Magst du es gleich mal ausprobieren und dann vielleicht auch einen PullRequest erstellen?

Dir noch ein schönes Wochenende!

**Comment by sboutizla** [comment]
Geschlossen
