### ISSUE TITLE
TestEintrag

### ISSUE THREAD

**Issue by raimundl** [LernMoment/einstieg-csharp-taschenrechner#36]

**Comment by raimundl** [comment]
Versuche mich nun auch auf GitHub

**Comment by suchja** [comment]
@raimundl Super, dass du da bist!!! Herzlich Willkommen und Glückwunsch zu deinem ersten Issue!

Das du es auch schließen kannst, hast du ja schon heraus gefunden ;-)! Der nächste Schritt ist dann, dass du einen PullRequest erstellst.

Viele Grüße aus Bielefeld
Jan von [LernMoment.de](https://www.lernmoment.de)
