### ISSUE TITLE
Issues Test

### ISSUE THREAD

**Issue by datenschuster** [LernMoment/einstieg-csharp-taschenrechner#38]
Dann mal Wasser 💦 unterm Kiel

**Comment by suchja** [comment]
Sehr gut 😊! Herzlich willkommen bei LernMoment und natürlich auf GitHub!

Als Autor kannst du das Issue auch selber schließen. Magst du es gleich mal probieren?

Viele Grüße aus Bielefeld 
Jan von LernMoment.de
