### ISSUE TITLE
Task: erstelle Issue

### ISSUE THREAD

**Issue by LittleRobby** [LernMoment/einstieg-csharp-taschenrechner#39]
Mission accomplished.

**Comment by suchja** [comment]
@LittleRobby Perfekt! Willkommen auf GitHub und vielen Dank, dass du dich mit mir und meinen Materialien auf LernMoment.de in GitHub einarbeitest.

Als Autor eines Issues kannst du es auch selber wieder schließen. Magst du es direkt mal ausprobieren?
