### ISSUE TITLE
Test exercise: create an issue

### ISSUE THREAD

**Issue by seal-js** [LernMoment/einstieg-csharp-taschenrechner#40]
@suchja
Hi, I follow your GitHub tutorila on Udemy.
It's great. Thanks.

**Comment by suchja** [comment]
@seal-js Hello and welcome to GitHub and LernMoment.de!

Thank you so much for participating in my tutorial! It‘s fantastic that you are also doing the exercises. By the way, you as author of this issue are also allowed to close it. would you like to try it?

**Comment by seal-js** [comment]
@suchja I'll do it.
Status closed.

**Comment by suchja** [comment]
Don't forget to also try a PullRequest!!!!
