### ISSUE TITLE
Danke für deine Arbeit - Ein Testissue

### ISSUE THREAD

**Issue by nils237** [LernMoment/einstieg-csharp-taschenrechner#41]
Vielen Dank
#37

**Comment by suchja** [comment]
@nils237 Sehr Gerne!!! Freut mich sehr, dass du dabei bist!

Viele weitere Ressourcen zu professioneller Softwareentwicklung und GitHub findest du auf [LernMoment.de](https://www.lernmoment.de). 

Wenn du magst, dann kannst du dieses Issue wieder schließen. Das kann nämlich sowohl der Autor (also du) wie auch der Projektinhaber (also ich). Danach hoffe ich natürlich noch auf einen PullRequest von dir. Damit du auch das aktive Ändern einmal geübt hast.

Viele Grüße aus Bielefeld
Jan

**Comment by suchja** [comment]
PS: Danke für deine Bewertung des Tutorials auf Udemy!!!
