### ISSUE TITLE
Kann man auf GitHub Bilder bzw. Videos ablegen?

### ISSUE THREAD

**Issue by brackal** [LernMoment/einstieg-csharp-taschenrechner#42]
Wenn es kein Programmier Projekt sein soll, sondern irgendein Bastel- Projekt, dann möchte man Fotos etc. ablegen. Geht das?

**Comment by suchja** [comment]
Du kannst eigentlich alle Dateien dort ablegen. Viele Vorteile bekommst du allerdings nur bei **nicht** binären Dateien. Wenn du beispielsweise die Unterschiede zwischen zwei Versionen einer Datei anschauen willst, geht das bei binären Dateien nicht. 
Weiterhin gab es manchmal Probleme bei großen Dateien. 

Du müsstest es also am besten mal ausprobieren.

**Comment by brackal** [comment]
Ich habe gelesen, dass GitHub von Microsoft aufgekauft wurde. Kann man GitHub weiterhin nutzen auch in Zukunft oder wird die Plattform irgendwann geschlossen? Ist Azure so was ähnliches wie GitHub?

**Comment by suchja** [comment]
Ja, Microsoft hat vor einigen Monaten GitHub gekauft. Eine definitive Antwort geben kann ich dir nicht, aber ich glaube nicht, dass GitHub innerhalb der nächsten Jahre geschlossen wird.
Microsoft ist sehr bemüht im Open Source Bereich Fuß zu fassen und ist schon seit einigen Jahren mit der größte Nutzer von GitHub überhaupt.

Azure ist viel mehr als GitHub. Azure kannst du eher mit Amazon AWS vergleichen. Es ist eine Art Cloud-Plattform mit allem was ein Entwickler braucht um Cloud-basierte Anwendungen zur Verfügung zustellen.
Microsoft hat schon seit Jahren eine Art Konkurrenten zu GitHub und der nennt sich aktuell *Azur DevOps*. Es ist also ein Teil von Azure und kann einiges was GitHub kann und auch noch einiges mehr. Der Hauptunterschied liegt darin, dass *Azure DevOps* (vorher hieß es *Visual Studio Team Services*), "nur" private Projekte kann. Du kannst also wunderbar alleine oder mit einem Team an deinem Projekt arbeiten, aber du kannst dein Projekt nicht wie auf GitHub "allen" zur Verfügung stellen.

Ja, es hilft, wenn man die Issues thematisch trennt und für neue Themen ein neues Issue mit entsprechendem Titel erstellt. Ist aber auch nicht so schlimm ;-)!

**Comment by brackal** [comment]
Danke für die ausführliche Antwort!
