### ISSUE TITLE
Das ist nur ein Test

### ISSUE THREAD

**Issue by GrazDesign** [LernMoment/einstieg-csharp-taschenrechner#47]
@suchja Hallo Jan, das wollte ich nur testen. 

Danke für das kostenlose Video. 

Grüße aus Norden.

**Comment by suchja** [comment]
Hallo Paul,

sehr gerne und herzlich willkommen bei [LernMoment](https://www.lernmoment.de) und auf GitHub. Freut mich insbesondere, dass du nicht nur die Videos anschaust, sondern auch aktiv wirst ;-)!!!

Als Autor eines Issues kannst du dieses auch wieder schließen. Magst du es vielleicht ausprobieren?

Viele Grüße aus Bielefeld
Jan

**Comment by GrazDesign** [comment]
Hallo Jan,

leider kann ich das nicht finden. Kannst du mir vielleicht helfen? Danke im
Voraus.
[image: image.png]

Am Do., 16. Mai 2019 um 15:32 Uhr schrieb Jan Suchotzki <
notifications@github.com>:

**Comment by suchja** [comment]
Hallo Paul,

tut mir leid, dass ich mich erst jetzt melde!

Wenn du einen Kommentar eingibst, dann kannst du auswählen zwischen den Buttons `Close and comment` und `Comment`. Die erste Option schließt das Issue. Dieses siehst du dann auch oben auf der Webseite. Dort findet sich dann nicht mehr ein grüner `Open` Hinweis, sondern ein roter `Closed`.
