### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by adsoe** [LernMoment/einstieg-csharp-taschenrechner#48]
Hallo, auch von mir ein Test-Issue.
Vielen Dank für den kostenlosen Kurs!

**Comment by suchja** [comment]
@adsoe PERFEKT! Herzlich willkommen bei [LernMoment.de](https://www.lernmoment.de) und auf GitHub!

Als Author dieses Issues kannst du es auch selber wieder schließen. Magst du es mal ausprobieren?

**Comment by adsoe** [comment]
aber sicher :)
