### ISSUE TITLE
Ein Issue für die Welt

### ISSUE THREAD

**Issue by sirditschonweg** [LernMoment/einstieg-csharp-taschenrechner#49]
Moin aus Hamburg,

ich danke für den Kurs und das ich hier meinen Kommentar hinterlegen kann.

Gruß

**Comment by suchja** [comment]
@sirditschonweg Perfekt! Freut mich das es dir gefällt und du auch die Übung machst! Als Autor eines Issues kannst du übrigens das Teil auch wieder schließen. Magst du es mal direkt ausprobieren?

Viele Grüße aus Bielefeld
Jan von LernMoment.de
