### ISSUE TITLE
Der Test zum Video

### ISSUE THREAD

**Issue by Beeb2402** [LernMoment/einstieg-csharp-taschenrechner#50]
@suchja Hi finde es super das du kostenlos einen Überblick über github gewährst.

Gruß
Benny

**Comment by suchja** [comment]
Danke! Mache ich gerne. 

Wenn du magst, dann kannst du als Autor dieses Issue selber schließen. Einfach unten den entsprechenden Button betätigen. Magst du es probieren?

Viele Grüße 
Jan

**Comment by suchja** [comment]
Auch das läuft 😂! Wie du siehst kann man auch noch kommentieren, wenn das Issue schon geschlossen ist.

**Comment by Beeb2402** [comment]
Oh ja , so langsam kommt man rein.
Muss mich jetzt mal noch mit git beschäftigen.
