### ISSUE TITLE
TestIssue_1

### ISSUE THREAD

**Issue by meikon123** [LernMoment/einstieg-csharp-taschenrechner#51]
Hi this is just a test issue. Feel free to delete.

**Comment by suchja** [comment]
Brauche ich gar nicht löschen, sondern du kannst das Issue einfach schließen und damit verschwindet es aus Liste der "Offenen Issues", weil sich sein Zustand auf "Closed" ändert.

Sowohl du als Author wie auch ich als Projektinhaber können ein Issue schließen. Das du es auch schließen kannst ist praktisch falls du mal versehentlich ein Issue schreibst und findest dann die Antwort doch selber, oder ;-).

**Comment by suchja** [comment]
@meikon123 Probier doch mal aus dass Issue zu schließen.
