### ISSUE TITLE
Wann kommt Release 2.0 (Achtung: Nur zu Übungszweck erstellt)

### ISSUE THREAD

**Issue by AndreasRaisl** [LernMoment/einstieg-csharp-taschenrechner#52]
@suchja 
#51

**Comment by suchja** [comment]
@AndreasRaisl Moin, herzlich willkommen bei GitHub und natürlich auf [LernMoment.de](https://www.lernmoment.de). Bist du über einen meiner Kurse auf dieses Repository gestossen?

Wie gefällt dir GitHub? Hast du noch weitere Fragen dazu?

**Comment by suchja** [comment]
Auch cool, dass du direkt die Links zu anderen Issues ausprobierst!
