### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by TonWin23** [LernMoment/einstieg-csharp-taschenrechner#54]
Vielen Dank für das gelungene Videotraining auf Udemy.

**Comment by suchja** [comment]
@TonWin23 Sehr gerne! freut mich, dass es dir gefällt.

Als Autor dieses Issues kannst du es auch selber wieder schließen. Magst du es mal ausprobieren? 

Viele Grüße aus Bielefeld
Jan von [LernMoment.de](https://www.lernmoment.de)
