### ISSUE TITLE
Test Issue 

### ISSUE THREAD

**Issue by Makla1** [LernMoment/einstieg-csharp-taschenrechner#55]
#47 #53 #52 Danke

**Comment by suchja** [comment]
Willkommen auf GitHub! Freut mich sehr, dass du einen der Kurse von [LernMoment.de](https://www.lernmoment.de) belegt hast.

In deinem Account habe ich das GitHub Learning Lab gesehen. Wie gefällt es dir? Ich kannte es bisher noch nicht und finde es vom Ansatz her sehr cool. Taugt es für dich zum lernen?

Als Autor dieses Issues kannst du nicht nur antworten, sondern das Issue auch schließen. Magst du es mal ausprobieren?

Viele Grüße aus Bielefeld 
Jan von LernMoment.de

**Comment by suchja** [comment]
@Makla1 das direkte ansprechen einer Person mithilfe des `@` ist gut, damit bei vielen Aktivitäten in einem Account deine Nachricht nicht untergeht. Ich bin gerade nur zufällig auf dein Issue hier gestoßen.
