### ISSUE TITLE
Test Issue (GitHub Erweiterung für Visual Studio)

### ISSUE THREAD

**Issue by hk1000** [LernMoment/einstieg-csharp-taschenrechner#56]
Um GitHub einfach mit Visual Studio 2015 zu nutzen, lade dir einfach die GitHub Erweiterung für VS runter.

Extras-> Extensions und Updates
Klicke dann auf Online und suche nach Github.

Danach kann man auch bestehende Projekte leicht Versionierbar machen.

**Comment by suchja** [comment]
@hk1000 herzlich willkommen auf GitHub 🎉! Freut mich sehr, dass dir mein Kurs scheinbar geholfen hat und das du auch die Übungen machst.

Vielen Dank für deinen Hinweis mit der Extension. Da muss ich wirklich langsam mal die Videos etwas überarbeiten.

Wusstest du schon, dass du als Autor dieses Issues es auch wieder schließen kannst? Magst du es vielleicht direkt ausprobieren?

Viele Grüße und hoffentlich bis bald bei deinem ersten PullRequest
Jan von LernMoment.de
