### ISSUE TITLE
Tutorial: Grundlagen von GitHub

### ISSUE THREAD

**Issue by Juergen-Busch** [LernMoment/einstieg-csharp-taschenrechner#57]
Hallo @suchja,

ich arbeite gerade den Kurs "Grundlagen von GitHub - Fork, Pull Request und Co.". Danke für das Bereitstellen.

Grüße! Jürgen

**Comment by suchja** [comment]
@Juergen-Busch vielen Dank! Freut mich sehr, dass dir das Tutorial ein wenig weiterhelfen konnte und das du mit der Übung den praktischen Einstieg gestartet hast.

Als Autor dieses Issues kannst auch du das Issue wieder schließen. Magst du es vielleicht mal ausprobieren?

Viele Grüße aus dem regnerischen Bielefeld
Jan von [LernMoment](https://www.lernmoment.de)

**Comment by Juergen-Busch** [comment]
Übung beendet. Issue wird geschlossen.

**Comment by suchja** [comment]
Perfekt. Wie du nun hier siehst kannst sogar auch bei bereits geschlossenen Issues einen Kommentar hinterlassen.
