### ISSUE TITLE
Zu "Tutorial: Grundlagen von GitHub" - Issue-Übung

### ISSUE THREAD

**Issue by GitHub-user-123456789** [LernMoment/einstieg-csharp-taschenrechner#59]
1.) Die Folge-Bezeicnungen neben dem "Udemy"-Logo und in der  Liste "Course-Content" weichen voneinander ab. Das irritiert u.U., weil man parallel in der IDE und in GitHub das Vorgeführte nachzuvollziehen versucht und sich immer wieder neu orientieren muß.

![Folge8](https://user-images.githubusercontent.com/54154702/71785669-a684a480-3002-11ea-9a28-43ee088a9cdb.jpg)

2.) Folge 1, Resource "Wie Du Git mit Visual Studio verwendest" ist veraltet. Die Vorgehensweise ist in VS 2019 eine andere. Man kann unter Datei/Neu ein neues Repository erzeugen, wobei mir nicht klar ist, wie ich das einem neuen Projekt zuordne ( Auswahl des Repository als Projekt-Verzeichnis? ). Oder man erzeugt ein neues Projekt und hat die Möglichkeit unten rechts am Bildschirm "Zur Quellcodeverwaltung hinzufügen" anzufahren. Übernimmt man ein Projekt aus GitHub mittels Zip-Archiv, erzeugt man händisch ein Projekt-Verzeichnis und fährt dieses Projekt an ( .sln-Datei ), erkennt Git nicht die bereits vorhandene .git*-Dateien. Wie teilt man diese Git mit? Oder man muß einen anderen Weg gehen.

3.) Die 8. Folge ist veraltet. Im Team-Explorer erscheinen Begriffe wie "Stashes", "Gestagete Änderungen", "Gestageter Commit", "Stashes", "Stash ausführen" usw.

![VS2019-TeamExplorer-Änderungen](https://user-images.githubusercontent.com/54154702/71785449-ee55fc80-2fff-11ea-963c-7ac19ec9e6b0.jpg)

Was hängt wie mit was zusammen?

Ebenso gibt es Abweichungen im Kontextmenü. Ein Sreenshot gelingt mir nicht. "Commit..." wird nunmehr über den Menüpunkt "Quellcodeverwaltung" des Kontextmenüs egal wo im im Code angefahren.

4.) Bezugnehmend auf die Erwiederung auf Issue #58 " Versionstände, Versionsbaum?": Ein Zahnrad sehe ich nicht; ebensowenig einen Tab oder Menue _Label_, s.d. ich diesen Issue nicht z.B. als Frage kennzeichnen kann. ( Die dargebotenen Möglichkeiten hängen nicht davon ab, ob man sich im _Write_- oder im _Preview_-Modus befindet. )

![GitHub-Label](https://user-images.githubusercontent.com/54154702/71785490-5efd1900-3000-11ea-9fe7-25c313129261.jpg)

**Comment by suchja** [comment]
@GitHub-user-123456789 Vielen Dank für deine umfangreiche Rückmeldung zum Kurs. Hat sicherlich einiges an Zeit gekostet!

Ich weiß, dass sich in VS2019 einiges bezüglich GitHub geändert hat und das wird in den kommenden Wochen auch mit in das Tutorial einfließen. Neue Videos sind geplant und werde auch passend veröffentlicht.

Zu deinen Fragen:
1.) Ich bin mir nicht sicher ob ich dich richtig verstehe. Der Schriftzug neben dem Udemy-Logo enthält den Kurstitel (soweit ich das bisher gesehen habe). Wenn du etwas anderes beobachtest, dann melde dich bitte nochmals. Ich kann da allerdings auch nur den Udemy-Support einschalten.
2.) Da hast du absolut Recht. Der Artikel [Versionskontrolle mit Git und VS2015](https://www.lernmoment.de/alle/git-mit-visual-studio/) passt nicht zu VS2019. Grundsätzlich hat sich allerdings gar nicht so viel geändert. Der einfachste Weg ist, dass du ein Projekt erstellst (dabei gibt es nicht mehr die Möglichkeit es direkt mit Git zu erstellen), dann "Der Quellcodeverwaltung hinzufügen" auswählen und letztlich mit GitHub synchronisieren. Wenn du die GitHub-Erweiterung installiert hast, kannst du dort eines der bestehenden Projekte auf GitHub auswählen oder auch direkt ein neues anlegen (glaube ich). Weitere Details dazu werde ich in einem neuem Video vorstellen.
3.) Ja, VS2019 unterstützt nun auch den `Stash` von Git. Der Rest sollte sich nicht verändert haben. Das Staging gibt es schon lange in VS und ist ein wichtiger Bestandteil von Git. Ein Anwendungsfall ist, wenn du viele Änderungen hast und möchtest nicht alles zusammen in einen Commit kippen. Dann suchst du dir einige Änderungen aus und "stagest" diese. Sie werden quasi in einen speziellen Bereich verschoben. Alles was in diesem Bereich liegt wird mit dem Commit "abgegeben". Die restlichen Änderungen werden dir immer noch angezeigt und du kannst sie im nächste Commit abgeben.
Der Weg wie ich es im Video zeige ist eigentlich der Standardweg von VS (auch in Version 2019) und überspringt das Staging.
4.) Sollte hoffentlich nun in #58 beantwortet sein.

Ich versuche so schnell wie möglich die Videos aufzunehmen und bereitzustellen.

**Comment by GitHub-user-123456789** [comment]
zur 1. Frage - Vorschlag für den Vido-Titel im Beispiel: "Tutroial: Grundlagen von GitHub - Folge 8 - Einen Pull Request erstellen". Der Titel im Beispiel aber umfaßt inhaltlich die Folgen 7, 8 und 9. Das ist durchaus ok, wenn die Aufteilung der Videos in Abschnitte dem auch so entspräche. Dem ist aber nicht so, denn die Folgen  5 und 6 haben mit "Fork, Pull-Request und Co." in dieser Sicht nichts zu tun. Eine alternative Lösung wäre, ggf. die Sections in Abschnitte zu unterteilen, die dann im Video-Titel refernziert werden.

Ich schließe i.S. einer Übung dieses Issue, denn alles weitere klärt sich in #58.
