### ISSUE TITLE
Einfach ein Test-Issue

### ISSUE THREAD

**Issue by helloourson** [LernMoment/einstieg-csharp-taschenrechner#60]
Wow mein erstes Issue. GitHub eine Welt die sich mir bis jetzt noch nicht erschlossen hat.
Dank der Hilfe von  @suchja mach ich meine ersten Schritte.

- Erste Frage

- Zweite Frage

**Comment by suchja** [comment]
@helloourson Herzlich Willkommen auf GitHub und vielen Dank, dass du ein Tutorial / Kurs von LernMoment belegt hast. Entschuldige, dass ich erst jetzt antworte 😔. 

Glückwunsch zu deinem ersten Issue und den PullRequest bearbeite ich auch sofort. Sofern du noch Fragen hast (du schreibst, dass sich die GitHub-Welt noch nicht erschlossen hat), kannst du sie mir gerne jederzeit stellen. Sofern du wir hier @suchja verwendest sehe ich die Frage sofort und werde dann auch schneller mit einer Antwort sein.

Wenn du magst, kannst du dieses Issue noch schließen. Das kannst nämlich du als Autor und ich als Projektinhaber.

**Comment by suchja** [comment]
Bestimmt hast du auch so herausgefunden wie ein Issue zu schließen ist. Daher schließe ich es mal selber 😁!
