### ISSUE TITLE
erste Test-Issue

### ISSUE THREAD

**Issue by chrisfrie** [LernMoment/einstieg-csharp-taschenrechner#61]
@suchja vielen Dank für dein Lernvideo bei Udemy. Ich hoffe, das ich damit das bisherige Rätsel "Github" endlich besser verstehe. Nun die hoffentlich ersten Erfolge. Vielen Dank dafür.

**Comment by suchja** [comment]
@chrisfrie Herzlichen Glückwunsch zum ersten Issue und willkommen auf GitHub und bei den Tutorials und Kursen von [LernMoment.de](https://www.lernmoment.de). Das sieht ja soweit schon mal sehr gut aus.

Als Autor dieses Issues kannst du das Issue auch selber wieder schließen. Das Recht dazu haben nur der Autor und der Projektinhaber (also ich ;). Magst du es vielleicht gleich ausprobieren?

Der nächste Schritt ist dann, dass du einen PullRequest machst. Ich warte bis dahin ;-)!

Viele Grüße aus (dem wieder aufgetauchten) Bielefeld
Jan von LernMoment.de

PS: Wenn du noch mehr über GitHub erfahren möchtest, hilft dir vielleicht mein Artikel ["Was ist GitHub"](https://www.lernmoment.de/alle/was-ist-github/).

**Comment by suchja** [comment]
Bestimmt hast du auch so herausgefunden wie ein Issue zu schließen ist. Daher schließe ich es mal selber 😁!
