### ISSUE TITLE
First Step with GitHub

### ISSUE THREAD

**Issue by Liatthey** [LernMoment/einstieg-csharp-taschenrechner#62]
Ich habe heute angefangen mit deinem Online Kurs auf Udemy und bin begeistert. Du erklärst es wirklich unglaublich gut und ich hoff, dass ich bei dem Python Programmiervideo auch so gut mitkommen werde! Danke dafür!!!

**Comment by suchja** [comment]
@Liatthey Mmmmoin und herzlich willkommen auf GitHub und bei den Tutorials und Kursen von [LernMoment](https://www.lernmoment.de). Vielen Dank! Freut mich sehr, dass ich helfen kann.

Hier noch ein Tipp: Als Autor eines Issues kannst du dieses, genau wie der Projektinhaber (in diesem Fall also ich), auch selber wieder schließen. Magst du es an diesem Issue mal ausprobieren? Klicke einfach auf `Close` Button unter diesem Kommentar.

Ansonsten hoffe ich natürlich noch einen PullRequest von dir zu bekommen und wünsche dir viel Spaß beim Python lernen. Für welche der vielen Programmiervideos für Python hast du dich entschieden? Kannst du es empfehlen?

Viele Grüße
Jan von [LernMoment.de](https://www.lernmoment.de)

PS: Wenn du noch mehr über GitHub erfahren möchtest, hilft dir vielleicht mein Artikel "Was ist GitHub".

**Comment by Liatthey** [comment]
@suchja Hey, leider habe ich das Tutorial erst heute fertig geschafft, da mit dem Coronavirus und so alles ziemlich durcheinander war...dass mit dem Close Button werde ich nachher gleich ausprobieren, danke für den Tipp! Das PullRequest kriegst du heute natürlich auch noch, versprochen. Ich habe mich für den Kurs "Introduction to Python Programming" von Avinash entschieden, habe diesen allerdings noch nicht angefangen. Kennst du einen mit dem man Python lernt? 

Mit freundlichen Grüssen
Lia

**Comment by suchja** [comment]
Hey Lia, das hat doch schon mal perfekt geklappt 😄! Wie du siehst kannst du ein Issue auch wieder eröffnen (z.B. wenn du später feststellst, dass es doch noch nicht gelöst ist).

Bezüglich Python kann ich keine Empfehlungen geben. Bin mit .NET (also hauptsächlich C#) unterwegs.

**Comment by Liatthey** [comment]
Hey, ja es hat geklappt! Jejjjj...

Okey perfekt, dann werde ich das auch noch anschauen. Danke!
