### ISSUE TITLE
Erweiterung Programmfunktion "Modulo"

### ISSUE THREAD

**Issue by hannesa7x** [LernMoment/einstieg-csharp-taschenrechner#63]
@suchja Ich mache dieses Issue, da ich gerade die Aufgabe des kostenlosen Udemy - Kurss für Github von dir mache. Bezugnehmend auf #6 wollte ich fragen, ob vielleicht die Programmfunktion "Modulo" hinzugefügt wird? Also ganzzahliges Dividieren mit Rest, da es auch für Schüler sehr wichtig ist z.B. Umrechnung in verschiedene Zahlensysteme.

LG hannesa7x

**Comment by suchja** [comment]
@hannesa7x Willkommen auf GitHub und ich freue mich, dass du einen Kurs von [LernMoment.de](https://www.lernmoment.de/) belegt hast. Darf ich fragen wie du den Kurs gefunden hast?

Das mit dem Modulo ist eine super Idee! Ich denke darauf gehe ich mal im [Community Fragen Projekt](https://github.com/LernMoment/community-fragen/) ein.

Übrigens auch super, dass du hier direkt das andere Issue verlinkt hast. Hast du auch gesehen was dann in dem anderen Issue passiert?

**Comment by hannesa7x** [comment]
Ich finde den Kurs sehr gut. Er hat eine angenehme Länge und bietet etwas Abwechslung. Sehr cool finde ich, dass du da deine anderen Kurse einbindest. So profitierst du und andere sehr davon. Generell kommt das Thema Git/Github gerade sehr gelegen, da wir das in der Schule gerade mit den Schülern machen. 

Ist interessant was da passiert, wenn man ein anderes Issue verlinkt. Danke für den Tipp

**Comment by suchja** [comment]
Hört sich spannend an. An was für einer Schule bist du aktiv, dass dort GitHub gemacht wird? Finde ich super!!!

Als Autor eines Issues, kannst du dieses (genau wie der Projektinhaber) auch wieder schließen. Magst du es mal ausprobieren?

**Comment by hannesa7x** [comment]
Es ist eine technologische Fachoberschule. Ich finde das sehr wichtig und interessant mit git und GitHub zu arbeiten. Ok probier ich aus, das Issue zu schließen. LG und Danke für die Hilfe
