### ISSUE TITLE
Erster Issue

### ISSUE THREAD

**Issue by ConnyGruen** [LernMoment/einstieg-csharp-taschenrechner#65]
#60 @suchja Das ist auch mein erster Issue. Hoffentlich auch bald mit wertvollem Input. 
Danke für den verständlichen Kurs

**Comment by suchja** [comment]
@ConnyGruen Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Vorher kannst du allerdings noch dieses Issue schließen. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Das kannst du mit dem Button unten auf dieser Seite mache. Probier es doch mal aus.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by suchja** [comment]
Perfekt! Übrigens, auch wenn ein Issue geschlossen ist, kannst du (oder alle anderen) daran noch weiterhin Kommentare abgeben.

**Comment by ConnyGruen** [comment]
@suchja gut zu wissen - hast du zufällig meine Fragestellung im Pull Request zur Teilnehmergrüße Aufgabe gesehen? - Danke schonmal

**Comment by suchja** [comment]
Gerne! Ich habe weder deine Fragestellung noch deinen PullRequest gesehen. Das liegt allerdings daran, dass der scheinbar nicht raus gegangen ist.

In deinem Commit schreibst du, dass du dir nicht sicher bist ob du das Einfügen des GitHub Accounts geschafft hast. Was meinst du damit? Vielleicht kannst du mir in ein paar Stichpunkten schreiben welche Schritte du in Visual Studio gemacht hast und wo etwas unklar ist. 

Hier mal 2 Artikel die dir vielleicht helfen ein paar allgemeine Fragen zu beantworten:
[Versionskontrolle mit Git und Visual Studio 2019](https://www.lernmoment.de/alle/git-mit-visual-studio-2019/)
[Synchronisiere dein Visual Studio 2019 Projekt mit GitHub](https://www.lernmoment.de/alle/projekt-auf-github-veroeffentlichen/)

**Wichtig:** In den Artikeln geht es nicht um einen PullRequest! Es geht darum, dass du dein eigenes Visual Studio 2019 Projekt mit git verwaltest und auf GitHub veröffentlichst. Ich denke die Artikel helfen dir aber nochmals ein wenig die Zusammenhänge zu sehen.

**Comment by suchja** [comment]
Ich war zu schnell mit meinem Kommentar! Der PullRequest ist nicht rausgegangen, weil zwar die Änderung als Commit per git gemacht hast und der Commit auch auf GitHub sichtbar ist, aber du müsstest noch den Button "PullRequest erstellen" drücken.

Momentan fehlt der Schritt der die Änderungen an deinem Fork an "mein" Projekt zur Veröffentlichung schickt.

**Comment by suchja** [comment]
Wenn du noch Fragen/Probleme hast, dann melde dich bitte.
