### ISSUE TITLE
Code Struktur tiptop

### ISSUE THREAD

**Issue by juergli** [LernMoment/einstieg-csharp-taschenrechner#66]
@suchja Mir ist aufgefallen, dass Dein Code sehr schön strukturiert ist. Das gefällt mir sehr gut - so ist der Code sehr gut lesbar.
Somit habe auch ich einen ersten Issue auf Github erstellt :-)

**Comment by suchja** [comment]
@juergli Super! Vielen Dank! Solch eine Rückmeldung freut mich natürlich sehr 😊! Entwickelst du selber in C#?

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Vorher kannst du allerdings noch dieses Issue schließen. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Das kannst du mit dem Button unten auf dieser Seite mache. Probier es doch mal aus.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by suchja** [comment]
Bestimmt hast du auch so herausgefunden wie ein Issue zu schließen ist. Daher schließe ich es mal selber 😁!
