### ISSUE TITLE
Test Issue - Danke für die Einführung

### ISSUE THREAD

**Issue by nilorac** [LernMoment/einstieg-csharp-taschenrechner#67]
Ich wollte nur mal ein Test Issue erstellen. 

Viele Grüße

**Comment by suchja** [comment]
@nilorac Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Nachdem du nun diese Übung absolviert hast und bereits einen PullRequest erstellt hast, bist du auch schon durch mit den Übungen.

Als letzte Aktivität kannst du noch dieses Issue schließen. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Das kannst du mit dem Button unten auf dieser Seite mache. Probier es doch mal aus.

Danach erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by nilorac** [comment]
Erledigt.
