### ISSUE TITLE
Erster Issue

### ISSUE THREAD

**Issue by myrepo32** [LernMoment/einstieg-csharp-taschenrechner#68]
@suchja gute Erklärung!

**Comment by suchja** [comment]
@myrepo32 Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Vorher kannst du allerdings noch dieses Issue schließen. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Das kannst du mit dem Button unten auf dieser Seite mache. Probier es doch mal aus.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by suchja** [comment]
Bestimmt hast du auch so herausgefunden wie ein Issue zu schließen ist. Daher schließe ich es mal selber 😁!
