### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by Nuralieva-Elnura** [LernMoment/einstieg-csharp-taschenrechner#69]
@suchja herzlichen Dank für die Video-Erklärung.

**Comment by suchja** [comment]
@Nuralieva-Elnura Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Vorher kannst du allerdings noch dieses Issue schließen. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Das kannst du mit dem Button unten auf dieser Seite mache. Probier es doch mal aus.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by suchja** [comment]
@Nuralieva-Elnura ich schließe dieses Issue einfach mal. Wenn du noch Fragen hast, kannst du dich gerne jederzeit melden.
