### ISSUE TITLE
Issue zum Testen

### ISSUE THREAD

**Issue by degrimmis** [LernMoment/einstieg-csharp-taschenrechner#70]
Hallo,

ich habe mir den Kurs auf Udemy angesehen und erstellen als Übung diesen Issue.
Ich habe recherchiert und #60 und weitere Issues aus dem selben Grund gefunden ;-)

LG Oliver

**Comment by suchja** [comment]
@degrimmis Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Vorher kannst du allerdings noch dieses Issue schließen. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Das kannst du mit dem Button unten auf dieser Seite mache. Probier es doch mal aus.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

PS: Vielleicht hast du bemerkt, dass durch die Verwendung eines # mit nachfolgender Nummer ein Link zu diesem Issue hergestellt wird. Klick doch mal auf die # 60 in deinem Text. 
---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by degrimmis** [comment]
Vielen Dank!
