### ISSUE TITLE
Issue Nr.1

### ISSUE THREAD

**Issue by Adrian0508** [LernMoment/einstieg-csharp-taschenrechner#71]
Du meinst man soll sein erstes Issue sofort machen. Also warum nicht XD Es gibt ja auch fast keine hier
#70 #69 #68 #67 #65 #33 etc.

**Comment by suchja** [comment]
@Adrian0508 🤣 ja, scheint als wäre dieses Projekt entweder sehr beliebt oder es gibt total viele Bugs 😁. 

Schön, dass du auch gleich das Verlinken probiert hast. Hast du gesehen was sich in den anderen Issues verändert dadurch, dass du hier einen Verweis auf sie eingefügt hast? Gehe doch nochmals in das Issue #70 und schau nach.

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Vorher kannst du allerdings noch dieses Issue schließen. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Das kannst du mit dem Button unten auf dieser Seite mache. Probier es doch mal aus.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by Adrian0508** [comment]
Das ist ja klasse. Ich habe die anderen wie Fork etc. Bei anderen Projekten gemacht. War ein Super Github Kurs!

**Comment by suchja** [comment]
DANKE!

Wie du siehst kannst du auch noch kommentieren wenn das Issue eigentlich geschlossen ist. Der Autor (in diesem Fall du) oder der Projektinhaber (in diesem Fall ich) können dann entscheiden ob das Issue wieder geöffnet wird.
