### ISSUE TITLE
neuer test issue

### ISSUE THREAD

**Issue by alos-source** [LernMoment/einstieg-csharp-taschenrechner#72]
# Description
this is my first issue on a github project.

## Repro  Steps
1. go to issues
2. write issuse
3. that's it ;-)

**Comment by suchja** [comment]
@alos-source Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Vorher kannst du allerdings noch dieses Issue schließen. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Das kannst du mit dem Button unten auf dieser Seite mache. Probier es doch mal aus.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by alos-source** [comment]
Danke für das Feedback und den Workshop!
