### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by Crashbandy** [LernMoment/einstieg-csharp-taschenrechner#73]
Nur ein Test für die Issue Funktion.

**Comment by suchja** [comment]
@Crashbandy Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Wie du schon gesehen hast, kann ein Issue geschlossen werden. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Es ist auch möglich, dass ein bereits geschlossenes Issue wieder geöffnet wird. Auch dazu haben wir beide die Berechtigung. Du kannst es ja mal ausprobieren, wenn du magst.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)
