### ISSUE TITLE
Erster git Issue

### ISSUE THREAD

**Issue by AndresRedondo87** [LernMoment/einstieg-csharp-taschenrechner#75]
Hallo Jan.

dies ist mein erster Issue als Eintragen-Test in Einstieg in C# Kurs.

Dazu wollte ich Dich @suchja fragen,  ob eine Aktualisierung bzw. kommentar über das Video "120. Sync - Quellcode von Visual Studio nach GitHub bringen". Meine aktuellen versionen von Github und VisualStudio sind etwas anderes asl was in den Video zu sehen ist und bin mir nicht sicher ob ich das HalloGitHub richtig nachgemacht habe (Klonen + Projekt neu offnen und Die Solution in die richtige Ordner erstellen). Das zweite Teil mit Commit und Sync hat toll geklappt, aber dafür müsste ich erst die Solution und "Unterordner" per Hand eine Stufe höher "schieben". 

Könntest du es für das letzte Git oberfläche und Visual Studio 2019 erklären?

Auch habe ich irgendwie "GitHubDesktop" herunterladen... ist es zu empfhelen oder mit Visual Studio + Browser ist genug?

Danke im Voraus,
Andrés

**Comment by suchja** [comment]
@AndresRedondo87 Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Vielen Dank für den Hinweis mit der veralteten Lektion im C# Kurs. Ich werde dort reinschauen und hoffentlich bald ein überarbeitetes Video bereitstellen. Bis dahin könnte dir vielleicht [dieser Artikel auf LernMoment](https://www.lernmoment.de/alle/projekt-auf-github-veroeffentlichen/) weiterhelfen.

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Vorher kannst du allerdings noch dieses Issue schließen. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Das kannst du mit dem Button unten auf dieser Seite mache. Probier es doch mal aus.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)

**Comment by suchja** [comment]
Bezüglich deiner Frage zu GitHub-Desktop:

Ich habe es vor einiger Zeit mal ausprobiert und kann sagen, dass mir persönlich VS und die Webseite reicht. Zusätzlich nutze ich unter iOS die GitHub-App. Darin kann ich sehr gut an den Issues arbeiten. Das ist allerdings nur notwendig, wenn du wirklich einiges an Issues wegschaffen musst.

**Comment by AndresRedondo87** [comment]
Vielen herzlichen Dank,
 ich werde dein Artikel nachlesen und wieder mitmachen bis ich es richtig hinkriege.
Der Github-Desktop scheint so gut wie eine Wiederholung von der Webseit, so ich werde es entweder vergessen oder deinstallieren.
