### ISSUE TITLE
Erstelle ein Issue

### ISSUE THREAD

**Issue by walidbbq** [LernMoment/einstieg-csharp-taschenrechner#77]
Hallo 
ich höre gerade deinen Kurs über GitHub.  Vielen Dank dass du den Kurs allen kostenlos zur Verfügung stellst. 
viele Grüße
Walid

@suchja 

https://www.udemy.com/course/github-tutorial-deutsch/learn/lecture/5869842#announcements

**Comment by suchja** [comment]
@walidbbq Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst.

Leider bin ich ziemlich im Rückstand mit meinen Antworten. Außerdem schreibe ich gerade einen Bot für GitHub der zukünftig aller neuen Teilnehmer direkt in Empfang nimmt. 

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Wie du siehst, kannst du ein Issue als Autor (oder als Projektinhaber, das bin dann hier ich) schließen. Es geht allerdings auch, dass du dein eigenes Issue wieder öffnest (z.B. wenn du später feststellst, dass es eigentlich doch nicht gelöst ist). Wenn du das auch ausprobieren magst, kannst du das gerne noch machen. Wäre schön, wenn du es anschließend auch wieder schließt, weil ich dann weniger zutun habe ;-).

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)
