### ISSUE TITLE
Ein Test-Issue

### ISSUE THREAD

**Issue by rs-ns** [LernMoment/einstieg-csharp-taschenrechner#78]
Hallo Jan,
ich höre nebenbei Deinen kostenlosen Kurs über github bei Udemy.

Was Wolfgang in #74 bzgl. Vorstellung zu Deiner Person geschrieben hat (... Der Kurs wirkt dadurch persönlicher.), empfinde ich auch so.

Danke und Viele Grüße Lars

**Comment by suchja** [comment]
@rs-ns Hallo und willkommen auf GitHub! Freut mich sehr, dass du eines der Tutorials / Kurse von [LernMoment.de](https://www.lernmoment.de/kurse) belegt hast und auch aktiv wirst. Danke für die Rückmeldung zum Kurs. Ich werde ihn baldmöglichst anpassen.

Nachdem du nun diese Übung absolviert hast, kannst du ja direkt weitergehen zum PullRequest!

Vorher kannst du allerdings noch dieses Issue schließen. Sowohl du als Autor wie auch ich als Projektinhaber sind berechtigt ein Issue zu schließen. Das kannst du mit dem Button unten auf dieser Seite mache. Probier es doch mal aus.

Jetzt erstmal viel Spaß beim weiteren erkunden von Github
Jan von [LernMoment.de](https://www.lernmoment.de/kurse/)

---

> Mehr Tutorials und Online-Kurse zu C#, GitHub und professioneller Softwareentwicklung findest du auf [LernMoment.de](https://www.lernmoment.de/kurse/)
