### ISSUE TITLE
Hallo von Udemy

### ISSUE THREAD

**Issue by assimatze** [LernMoment/einstieg-csharp-taschenrechner#8]
Hi Jan,

vielen Dank für den Kurs zu Github. hab schon lange ein passendes Tut gesucht das mir mit github auf die sprünge hilft.

Was ist eigentlich der unterschied von github zu gitlab?

Gruß

**Comment by suchja** [comment]
@assimatze Danke für deine tolle Rückmeldung. Freut mich, dass es dir gefällt!

Ich habe mich bisher noch nicht viel mit gitlab beschäftigt. Momentan hat eigentlich kein anderer Dienst so viele Open-Source-Projekt wie GitHub. [Dieser Artikel aus 2015](https://jaxenter.de/gitlab-vs-github-wer-bietet-mehr-23062) listet einige Unterschiede aus. Wie gut das zutrifft kann ich dir allerdings auch nicht sagen.

Wichtig ist halt, dass du git als Versionsverwaltung nutzt. Ob du dann auf einer Plattform wie GitHub aktiv bist, weil es dort die meisten Open-Source-Projekte gibt, Bitbucket nutzt weil es mit Jira ein verbreitetes Bugtracking-Tool hat oder vielleicht zu Microsoft mit Team Services tendierst, weil dort die Integration mit VisualStudio super ist, ist deine Entscheidung. Da musst du einfach überlegen was dir wichtig ist und wie du es nutzen willst.

Hoffe, dass hilft dir ein wenig.

Viele Grüße
Jan

PS: Wenn dir die Antwort reicht, dann schließe bitte dieses Issue. Ansonsten kannst du gerne weitere Fragen zu diesem Thema stellen.
