### ISSUE TITLE
Test-Issue

### ISSUE THREAD

**Issue by ghost** [LernMoment/einstieg-csharp-taschenrechner#9]
This is my first Issue, just ignore it 🗡

**Comment by suchja** [comment]
Well done ;-)!

As author of this issue you are also able to close it. Give it a try!

**Comment by Christian1967** [comment]
Das ist auch mein erstes Issue, bitte ignoriere dieses Issue

**Comment by suchja** [comment]
@Christian1967 Auch wenn es schon wieder einige Zeit her ist 😴 , wie sieht es aus mit dir und GitHub? Scheinbar hast du keinen Spaß / Bedarf dafür gefunden. Kann ich dich noch irgendwie unterstützen?

Vielen Dank für die Teilnahme an einem LernMoment-Kurs/Tutorial!

Viele Grüße
Jan von LernMoment.de

------------------------
🚀 NEU von LernMoment: Übe mit mir professionelle Softwareentwicklung in C# - [Starte jetzt zum Einführungspreis](https://www.udemy.com/csharp-uebungskurs-einfach-verschluesselt/?couponCode=GH-FOOTER-UROT-10)
