### ISSUE TITLE
Creating frist GitIssue  

### ISSUE THREAD

**Issue by MrNewGuy00** [LernMoment/einstieg-csharp-taschenrechner#91]
Hello  LernMoment team,

thanks for creating this tutorial for starting in the world of gitHub :).

**Comment by MrNewGuy00** [comment]
Closing  #91 issue  done

**Comment by suchja** [comment]
@rerdm Great! Now it's me "in person". The bot 🤖 isn't very trained until now 😁.
After closing you can also reopen the issue if you like.
After this nice progress on issues you can now go ahead and make your first PullRequest. 

All the best
Jan
