### ISSUE TITLE
Meine erste Issue

### ISSUE THREAD

**Issue by suadGhannoom** [LernMoment/einstieg-csharp-taschenrechner#92]
Hallo :)

**Comment by suchja** [comment]
@suadGhannoom Nun habe ich auch die Zeit mich persönlich bei dir zu melden. Super, dass du die Übung gemacht hast. Sofern du noch keinen PullRequest erstellt hast, wäre jetzt ein super Zeitpunkt dafür ;-).

Ich wünsche dir weiterhin viel Spaß auf GitHub und immer schön weiter lernen
Jan von [LernMoment.de](https://www.lernmoment.de)
